---
- name: Install and configure HAProxy
  block:
    - name: Install HAProxy
      yum:
        name: haproxy
        state: present
      notify:
        - restart haroxy      

    - name: Copy HAProxy configuration file
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: 'root'
        group: 'root'
        mode: '0644'
        validate: 'haproxy -c -f %s'
      notify:
        - reload haroxy
